### ISSUE TITLE
Too much recursion after few seconds and endless "loading" with online version

### ISSUE THREAD

**Issue by apupier** [stefanroeck/maven-performance-analyzer#1]
I'm trying to analyze the Maven output log from a large project ([Apache Camel](https://github.com/apache/camel)).

I generate the file with: `./mvnw clean install -D quickly -Dorg.slf4j.simpleLogger.showDateTime=true '-Dorg.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss,SSS' -Dorg.slf4j.simpleLogger.showThreadName=true > log-with-timestamp-andthreadname.txt` (quickly is a specific option to Apache Camel project to limit what is built, it already takes 15 minutes with dependencies already downloaded on my machine)

After uploading the log file to https://maven-performance-analyzer.vercel.app/ , there is an endless loading bar. When looking to the console, after few seconds there is an error:

```
running inside worker analyzerWorker-8fc32774.js:3:2892
Split string with 4681858 chars into 38606 lines analyzerWorker-8fc32774.js:3:12
parser total: 9035.69ms - timer ended analyzerWorker-8fc32774.js:3:402

too much recursion [analyzerWorker-8fc32774.js:3:1204](https://maven-performance-analyzer.vercel.app/assets/analyzerWorker-8fc32774.js)
    Symbol.match self-hosted:2450
    match self-hosted:3663
    In https://maven-performance-analyzer.vercel.app/assets/analyzerWorker-8fc32774.js:3
    Un https://maven-performance-analyzer.vercel.app/assets/analyzerWorker-8fc32774.js:3
    onmessage https://maven-performance-analyzer.vercel.app/assets/analyzerWorker-8fc32774.js:3
```
The file used: [log-with-timestamp-andthreadname.txt](https://github.com/user-attachments/files/15871166/log-with-timestamp-andthreadname.txt)

**Comment by apupier** [comment]
it is working when I use a local version of the site (so building locally and calling npm run start)

**Comment by stefanroeck** [comment]
Thanks for reporting, #3 should fix this. The Ui is still a bit sluggish for this huge log file, will see if we can improve this by reducing the number of rendered elements in the charts in a separate commit.
